nodak-v2/Nodak-FE

.github/workflows/storybook.yaml

> closes #26 
> 작업 내용에 대한 설명
pr 시 배포된 storybook url 을 코멘트 시켜 storybook 에 쉽게 접근할수있도록 합니다.
> 작업 결과물
> PR 전 체크해주세요.

[#26] Chore: storybook deploy comment 기능 추가

---

.storybook/preview.tsx
src/app/_components/Button/Button.tsx
src/stories/components/Button.stories.tsx

> closes #34 
> 작업 내용에 대한 설명
버튼 컴포넌트를 구현하였습니다.
> 작업 결과물
```ts
// global.css 
@tailwind base;
@tailwind components;
@tailwind utilities;
@layer base {
#layout-Root {
--primary-1: #c7b299;
--primary-2: #675640;
--gray-1: #f0f0f0;
--gray-2: #999999;
--gray-3: #333333;
--dark-1: #343a40;
--dark-2: #212529;
}
}
```
global.css 색상값을 storybook 에서도 사용할수있습니다.
```ts
// .storybook/preview.tsx
decorators: [
Story => (
<div id='layout-Root'>
<Story />
</div>
),
],
```
storybook 에서 tailwind 가 global.css 색상값 인식을 못 하여, 위코드를 추가해주었습니다.
> PR 전 체크해주세요.

[#34] Feat: button컴포넌트 구현

---

src/app/result/[postId]/_components/ProfileBlock.tsx
src/stories/components/ProfileBlock.stories.tsx

> closes #44 
post 결과 페이지에서 쓰일 ProfileBlock 컴포넌트를 구현했습니다.
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.

[#44] Feat: ProfileBlock 컴포넌트 구현

---

src/app/comment/_components/CommentInfo.tsx
src/app/comment/_components/PostComment.tsx
src/app/comment/page.tsx
src/stories/components/CommentInfo.stories.tsx
src/stories/components/PostComment.stories.tsx

> closes #47
> 피그마에 있는 디자인을 참고하여 댓글 페이지를 제작했습니다.
현재 UI만 진행하며 이후 댓글 추가, 삭제, 대댓글 여부 및 이용자 UI수정 등의 2차 코드 작성이 필요할 것 같습니다.
> 작업 결과물
<table>
<tr>
<th scope="col"><img src='https://github.com/nodak-v2/Nodak-FE/assets/104545906/0a502717-c0ea-4f49-810c-d0de6083be23'></td>
<th scope="col"><img src='https://github.com/nodak-v2/Nodak-FE/assets/104545906/32ea5711-df41-4102-9620-c305d07ffdd5'></td>
</tr>
</table>
```jsx
const GMTTime = 9 * 60 * 60 * 1000;  //시차 9시간 대응
<span className='text-sm text-gray-accent2'>
{new Date(createdAt.getTime() + GMTTime) //시간만 추출하여 시차 조정
.toISOString()
.replace('T', ' ')
.slice(0, -8)}
</span>
```
댓글 작성 시간을 Date 형식으로 받아와 포맷팅을 진행할 때 추가적인 형식 변환을 최소화 하기 위해
ISO 형식을 택했는데 시차가 발생하여 진행하게 된 코드입니다 DB 내 한국 시간으로 변경할 수 있다면 추후 변경될 수 있습니다.
tailwind 속성 적용만을 위한 …

[#47] 댓글페이지 UI 구현

---

src/components/Icon/type.ts

> closes #71
> Icon type관련 에러 수정 진행
> 작업 결과물
> PR 전 체크해주세요.

[#71] 에러 수정

---

src/utils/hooks/useTimeOffset.ts
src/utils/timeOffset.ts

> closes #67
> 시간 계산 함수 제작
> 
> 함수명, 시간 단위 명칭 등 수정사항이 있다면 알려주세요
> PR 전 체크해주세요.

[#67] 시간 계산 함수 제작

---

src/app/redirect/page.tsx
src/app/signin/page.tsx

> closes #77
> 작업 내용에 대한 설명
현재 백엔드 merge가 진행이 되지 않아서 당장은 로그인 상태를 확인할 수 없습니다.
추후에 백엔드 작업이 완료되면 바로 동작 할 수 있는 상태로 구현해놓았습니다. 
> PR 전 체크해주세요.

[#77] Feat: OAuth2

---

src/app/globals.css
src/app/layout.tsx
src/components/Button/Button.tsx
src/components/Drawer/index.tsx
src/components/TextInput/index.tsx
src/components/Textarea/index.tsx
src/components/Tooltip/Tooltip.tsx
src/stories/tailwind-configure/colors.stories.tsx
src/stories/tailwind-configure/fonts.stories.tsx
tailwind.config.js

> closes #99 
> 작업 내용에 대한 설명
- figma 에 있는 font 와 colors 이름에 맞춰 tailwind config 설정
- fonts ,colors 각각 스토리 작성
> 작업 결과물
> PR 전 체크해주세요.

[#99] Chore: tailwind 설정 추가

---

next.config.js
src/apis/image.ts
src/app/(post)/createPost/_component/ImageUploader.tsx
src/components/ImageUploadButton/hooks/useImageUpload.ts
src/components/ImageUploadButton/index.tsx

> closes #101 
> 작업 내용에 대한 설명
- 이미지 업로드 api 작성
- 이미지 업로드 컴포넌트 리팩터링 및 연결
> 작업 결과물
> PR 전 체크해주세요.
.env 환경변수가 추가되었습니다
notion fe 회의록에 올려두었습니다

[#101] Refactor: 이미지 업로드 컴포넌트 api 연결

---

src/app/(post)/createPost/_component/ImageUploader.tsx
src/components/Button/Button.tsx
src/components/Modal/ConfirmationModal.tsx
src/components/Modal/index.tsx

> closes #110 
> 작업 내용에 대한 설명
- 공용 모달 컴포넌트 구현
- 모달 컴포넌트를 활용한 confirmationModal 구현
- 이미지 삭제 버튼 기능에 confirmationModal 적용
> 작업 결과물
https://github.com/nodak-v2/Nodak-FE/assets/137467530/c09b8003-8c58-4d03-b0d6-30b3d1b558e9
> PR 전 체크해주세요.

[#110] Feat: 모달 컴포넌트 구현 및 적용

---

package.json
pnpm-lock.yaml
src/app/(post)/createPost/_component/ImageUploader.tsx
src/app/(post)/createPost/_component/PostForm/index.tsx
src/app/(post)/createPost/page.tsx
src/app/_components/Toast.tsx
src/app/layout.tsx

> closes #121 
> toast 컴포넌트 구현
임시로 게시물 작성페이지에 토스트 컴포넌트를 사용해봤습니다.
> PR 전 체크해주세요.

[#121] Feat: toast 컴포넌트 구현

---

src/app/layout.tsx

> closes #136
> 토스트 컴포넌트 위치 수정
> 작업 결과물
> PR 전 체크해주세요.

[#136] Style: 토스트 컴포넌트 위치 수정

---

src/app/(post)/result/[postId]/_components/Comments/CommentItem.tsx
src/app/(post)/result/[postId]/_components/Posting/index.tsx
src/app/_components/PostItem.tsx
src/utils/formatDate.ts

> closes #148
> 날짜 데이터 유틸함수 구현 및 적용
- 날짜 커스텀 정책
게시글 리스트 
- 당일: 00:00
- 과거(올해): MM. DD. 00:00
- 과거(올해X): YYYY. MM. DD. 00:00
댓글, 게시글
- 당일: 00:00
- 과거: YYYY. MM. DD. 00:00
> 작업 결과물
> PR 전 체크해주세요.

[#148] Feat: 날짜 커스텀 유틸 함수 구현 및 적용

---

package.json
pnpm-lock.yaml
src/app/(post)/result/[postId]/_components/Posting/PostingButton.tsx

> closes #144
* 디바운싱은 lodash 라이브러리를 활용했습니다.
* 낙관적 업데이트는 `react-query`의 `onMutation `을 활용해서 요청이전에 UI를 업데이트하려고 했으나,디바운싱 과정에서 마지막 요청만 API요청이 정상적으로 되기에, ui가 업데이트 되지 않는 오류가 생겼습니다. 이를 해결하기 위해 `useState`를 사용해 UI를 업데이트했습니다. 
> PR 전 체크해주세요.

[#144] Refactor: 게시글 좋아요에 디바운싱 및 낙관적 업데이트 적용

---

src/apis/postList.ts
src/app/(main)/constants.ts
src/app/(main)/utils.ts
src/app/(post)/createPost/_components/PostForm/index.tsx
src/app/(post)/search/page.tsx
src/app/_components/ChipContainer.tsx
src/app/page.tsx
src/hooks/useInfiniteScroll.ts

> closes #122 
- 인피니티 스크롤 훅 구현
- GET, postList api 에 useSuspenseInfiniteQuery 적용
> 작업 내용에 대한 설명
https://github.com/nodak-v2/Nodak-FE/assets/137467530/0aa3d0db-8528-438d-9c3d-2271ad917108
> 작업 결과물
> PR 전 체크해주세요.

[#119] Feat: 인피니티 스크롤 훅 구현

---

package.json
pnpm-lock.yaml
src/app/(post)/result/[postId]/page.tsx
src/app/(post)/search/page.tsx
src/app/page.tsx
src/app/users/[userId]/_components/PostingList.tsx
src/app/users/profile/(posting)/_components/PostingList/index.tsx

> closes #165 
> 작업 내용에 대한 설명
모바일 환경에서 리스트를 탐색 할 때 스크롤 하면서 자연스럽게 새로고침할수있도록 해주는 pull to refresh 방법을 적용하였습니다.
- "react-simple-pull-to-refresh" 패키지 추가
- main, search, resullt, Posting, notification 페이지에 적용
> 작업 결과물
https://github.com/nodak-v2/Nodak-FE/assets/137467530/3c967f22-acef-4648-a8bc-850d5eda3976
> PR 전 체크해주세요.
notification api 가 적용되어있지않아 TODO 로 주석처리해놨습니다.

[#165] Feat: pull to refresh 적용

---

src/app/(post)/result/[postId]/page.tsx
src/app/(post)/search/page.tsx
src/app/notification/page.tsx
src/app/page.tsx
src/app/users/[userId]/_components/PostingList.tsx
src/app/users/profile/(posting)/_components/PostingList/index.tsx

> closes #176 
> 작업 내용에 대한 설명
Pull To Refresh 컴포넌트를 적용하면서 생긴 아래 오류들을 해결하였습니다.
> 작업 결과물
> PR 전 체크해주세요.

[#176] Fix: 스크롤바가 하나 더 생기는 문제 수정

---

src/app/(post)/result/[postId]/_components/CommentList/CommentItem/CommentItemMenu/CommentReplyItemMenu.tsx
src/app/(post)/result/[postId]/_components/CommentList/CommentItem/CommentItemMenu/CommentRootItemMenu.tsx
src/app/(post)/result/[postId]/_components/CommentList/index.tsx

> closes #178 
> 작업 내용에 대한 설명
댓글 리스트가 0일경우 상태 메시지를 추가합니다.
상대의 댓글에대해 신고하기 옵션을 추가합니다.
> 작업 결과물
> PR 전 체크해주세요.
이전 pr 에 임시 신고 페이지를 추가하여 따로 신고페이지를 구현 하지 않았습니다

[#178] Feat: 댓글 기본 상태 메세지 추가 및 댓글 신고하기 옵션 추가

---

package-lock.json
src/app/(post)/createPost/error.tsx
src/app/(post)/result/[postId]/error.tsx
src/app/error.tsx
src/app/global-error.tsx
src/app/not-found.tsx
src/app/notification/error.tsx
src/app/users/error.tsx
src/components/EmptyPage/index.tsx
src/components/ErrorPage/index.tsx

> closes #164 
> 작업 내용에 대한 설명
> 작업 결과물
- Error 컴포넌트를 구현했습니다. 
- Next.js 파일 규칙(error.js, global-error.js)에 따라 errorFallback을  구현했습니다. 
- 각 에러 문구와 디자인은 디자이너분께 문의드린 상태입니다. 
피그마에 디자인이 없어서 우선 다시하기 버튼만 우선 적용하고 버튼 두개인 디자인은 아직 미적용 상태입니다. 
> PR 전 체크해주세요.

[#164] Feat: ErrorBoundary 설정 및 적용

---

src/app/users/[userId]/_components/PostingList.tsx
src/app/users/[userId]/page.tsx

> closes #187 
> 작업 내용에 대한 설명
기존에 PostList.tsx 에 있던 pullToRefresh 를 page.tsx 에 적용합니다.
> 작업 결과물
> PR 전 체크해주세요.

[#187] Refactor: pullToRefresh 를 페이지 레이어로 이동

---

src/app/(post)/createPost/page.tsx
src/app/(post)/result/[postId]/layout.tsx
src/app/(post)/search/page.tsx
src/app/report/layout.tsx
src/app/social/layout.tsx
src/app/users/[userId]/layout.tsx
src/app/users/profile/(posting)/_components/PostingList/index.tsx
src/app/users/profile/(posting)/layout.tsx
src/app/users/profile/(posting)/myComment/page.tsx
src/app/users/profile/(posting)/myLike/page.tsx
src/app/users/profile/(posting)/myPosting/page.tsx
src/app/users/profile/(posting)/myVoteHistory/page.tsx
src/app/users/profile/edit/page.tsx
src/components/Button/BackButton.tsx
src/components/Topbar/index.tsx
src/stories/components/Topbar.stories.tsx

> closes #192 
> 작업 내용에 대한 설명
- 뒤로가기 버튼 클릭시 홈이 아니라 뒤로가게 수정하였습니다.
- 프로필의 좋아요한글 댓글단글 투표한 글 목록은 내부에 글리스트가 없을경우 홈으로 이동하게하고, 내가 쓴글의 글 리스트가 없을경우에는 글쓰러가기로 변경하였습니다.
> 작업 결과물
> PR 전 체크해주세요.

[#192] Fix: 네비게이팅 관련 수정 사항 적용

---

src/app/chat/layout.tsx
src/app/notification/layout.tsx

> closes #196 
> 빌드에러 수정했습니다. 
> 작업 결과물
> PR 전 체크해주세요.

[#196] Fix: BackButton 프롭스 제거

---

src/app/(auth)/signin/page.tsx

Fix: 로그인 url 변경

---

src/apis/follow.ts

> closes #208 
> 작업 내용에 대한 설명
프로필 페이지에 팔로우 필로이 카운트가 언팔로우, 팔로우 후 무효화되지않는 문제가 발생하여 수정합니다.
> 작업 결과물
https://github.com/user-attachments/assets/0b8090f9-a2ca-4b93-9147-ffe10fbd914b
> PR 전 체크해주세요.

[#208] Fix: 프로필 페이지 팔로우 팔로이 카운트 캐시 오류 수정

---

src/app/layout.tsx
src/app/users/[userId]/hooks/useFollow.ts
src/components/MoreMenu/index.tsx

> closes #215 
> 작업 내용에 대한 설명
1. 드롭다운 메뉴에 커서 추가
2. 유저페이지 접근되지 않는 오류 해결
3. 앱아이콘 오류수정
> PR 전 체크해주세요.

[#215] Fix: 유저페이지 수정 및 그 외 간단한 작업

---

src/app/(post)/createPost/_components/PostForm/index.tsx
src/app/(post)/createPost/_components/VoteForm/index.tsx
src/app/globals.css
src/components/TimeInput/index.tsx

> closes #205 
> 작업 내용에 대한 설명
투표종료일 텍스트 변경(마감일 -> 종료일)
카테고리 선택 default 채널 변경 (채널 선택 -> 전체)
하단 버튼 투표 생성하기 -> 등록하기
투표 항목 이미지 클릭시 삭제
투표 종료일과 카테고리 모두 default처리 -> error에서 제외
투표 종료일 작성 시점 ~3일 후까지
투표 default종료일을 3일로 고정하려 했는데 계속 value값이 적용이 안되어서 
우선 이 task제외한 상태로 Pr올리겠습니다!
> 작업 결과물
> PR 전 체크해주세요.

[#205] Refactor:게시글 작성 페이지 수정
